@startuml
<style>
class {
  Padding 5
  RoundCorner 10
  HorizontalAlignment center
  LineThickness 0.5
  FontSize 12
  LineStyle 2
}

arrow {
  LineStyle 2
  LineThickness 0.75
}
</style>

skinparam {
  BackgroundColor Transparent
  ArrowFontColor DimGray
  CloudBorderColor DimGray
  class {
    BackgroundColor<<Aggregate Root>> #D5A6BD
    BackgroundColor<<Enum>> #D9D9D9
    BackgroundColor<<Value Object>> #B6D7A8
  }
}

hide circle
hide methods

class Question <<Aggregate Root>> {
  id: string
  questionSectionId: string
  position: integer
  industryIds: string[]
  label: string
  type: QuestionType
  options: string[]
  active: boolean
  createdAt: datetime
  createdBy: string
  updatedAt: datetime
  updatedBy: string
}

class QuestionSection <<Aggregate Root>> {
  id: string
  name: string
  active: boolean
  createdBy: string
  createdAt: datetime
  createdBy: string
  updatedAt: datetime
  updatedBy: string
}

enum QuestionType <<Enum>> {
  TEXT
  TEXTAREA
  MULTISELECT
  BOOLEAN
  RADIO
}

@enduml