@startuml
<style>
class {
  Padding 5
  RoundCorner 10
  HorizontalAlignment center
  LineThickness 0.5
  FontSize 12
  LineStyle 2
}

arrow {
  LineStyle 2
  LineThickness 0.75
}
</style>

skinparam {
  BackgroundColor Transparent
  ArrowFontColor DimGray
  CloudBorderColor DimGray
  class {
    BackgroundColor<<Aggregate Root>> #D5A6BD
    BackgroundColor<<Enum>> #D9D9D9
    BackgroundColor<<Value Object>> #B6D7A8
  }
}

hide circle
hide methods

class Vendor <<Aggregate Root>> {
  id: UUID
  userId: UUID
  tenantId: string
  companyName: string
  description: string
  logo: string
  companySize: string
  jobTitle: string
  phoneNumber: string
  faxNumber: string
  salesEmail: string
  schedulingLink: string
  website: string
  videoLink: string
  annualRevenue: string
  tagline: string
  businessHours: string
  yearEstablished: string
  languagesSpoken: string[]
  teamDescription: string
  teamPhoto: string
  address: Address
  socialMedia: SocialMedia
  industryIds: string[]
  serviceIds: string[]
  specificationIds: string[]
  regionsCovered: string[]
  certifications: string[]
  minProjectSize: string
  avgHourlyRate: string
  clientBudgets: string[]
  clientSizes: string[]
  clientEmployeeRanges: string[]
  clientLocations: string[]
  openToAnyLocation: boolean
  clientIndustries: string[]
  openToAnyIndustry: boolean
  questionnaire: Answer[]
  vendorVerificationStatus: VendorVerificationStatus
  reviewComment: string
  createdAt: datetime
  updatedAt: datetime
}

class Answer <<Value Object>> {
  questionId: UUID
  answer: String
}

enum VendorVerificationStatus <<Enum>> {
  INCOMPLETE
  PENDING
  VERIFIED
  BLOCKED
}

class VendorShowcase <<Aggregate Root>> {
  id: UUID
  vendorId: UUID
  tenantId: string
  projectName: string
  clientName: string
  description: string
  serviceIds: string[]
  duration: string
  resultsAndOutcomes: string
  active: boolean
  createdAt: datetime
  createdBy: string
  updatedAt: datetime
  updatedBy: string
}

class VendorDataPack <<Aggregate Root>> {
  id: UUID
  vendorId: UUID
  tenantId: string
  dataPackId: UUID
  createdAt: datetime
  updatedAt: datetime
  assignedBy: UUID
}

class Address <<Value Object>> {
  street: string
  city: string
  state: string
  postalCode: string
  country: string
}

class SocialMedia <<Value Object>> {
  linkedin: string
  twitter: string
  facebook: string
  instagram: string
  youtube: string
}

Vendor -right[hidden]- VendorVerificationStatus

@enduml
