export enum SourceType {
  REQUEST_FOR_QUOTE = 'REQUEST_FOR_QUOTE',
  REQUEST_FOR_PROPOSAL = 'REQUEST_FOR_PROPOSAL',
  SHOWCASE = 'SHOWCASE',
  QUOTATION = 'QUOTATION',
}

export enum QuotationSourceType {
  REQUEST_FOR_QUOTE = 'REQUEST_FOR_QUOTE',
  REQUEST_FOR_PROPOSAL = 'REQUEST_FOR_PROPOSAL',
}
