export enum ImportStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  ROLLED_BACK = 'ROLLED_BACK',
}

export enum ImportType {
  CONTACT_ENRICHMENT = 'CONTACT_ENRICHMENT',
  COMPANY_ENRICHMENT = 'COMPANY_ENRICHMENT',
  CONTACT_CREATE = 'CONTACT_CREATE',
  COMPANY_CREATE = 'COMPANY_CREATE',
}

export enum TargetEntity {
  LEAD_CONTACT = 'LEAD_CONTACT',
  LEAD_COMPANY = 'LEAD_COMPANY',
}

export enum RecordStatus {
  INSERTED = 'INSERTED',
  UPDATED = 'UPDATED',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
  NO_CHANGE = 'NO_CHANGE',
}
