export enum LeadQueryType {
  COMPANY_INDUSTRY = 'COMPANY_INDUSTRY',
  COMPANY_REGION = 'COMPANY_REGION',
  CONTACT_SENIORITY = 'CONTACT_SENIORITY',
  CONTACT_TITLE = 'CONTACT_TITLE',
  COMPANY_COUNTRY = 'COMPANY_COUNTRY',
  COMPANY_STATE = 'COMPANY_STATE',
  COMPANY_CITY = 'COMPANY_CITY',
}
