export enum LeadContactEventSourceType {
  CAMPAIGN = 'CAMPAIGN',
  CAMPAIGN_EMAIL = 'CAMPAIGN_EMAIL',
  CAMPAIGN_CONTACT = 'CAMPAIGN_CONTACT',
  CONTACT_EMAIL = 'CONTACT_EMAIL',
  LEAD_NOTE = 'LEAD_NOTE',
}

export enum LeadContactEventCategory {
  CAMPAIGN = 'CAMPAIGN',
  EMAIL = 'EMAIL',
  NOTE = 'NOTE',
}

export enum LeadContactEventType {
  CAMPAIGN_INITIATED = 'CAMPAIGN_INITIATED',
  CAMPAIGN_EMAIL_SENT = 'CAMPAIGN_EMAIL_SENT',
  CAMPAIGN_EMAIL_REPLIED = 'CAMPAIGN_EMAIL_REPLIED',
  EMAIL_SENT = 'EMAIL_SENT',
  EMAIL_OPENED = 'EMAIL_OPENED',
  NOTE_ADDED = 'NOTE_ADDED',
  NOTE_UPDATED = 'NOTE_UPDATED',
  NOTE_DELETED = 'NOTE_DELETED',
}
