name: Deploy

on:
  push:
    branches:
      - develop
      - main
      - static

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Inject Env Variables
        run: |
          echo "NEXT_PUBLIC_BASE_URL='${{ vars.BASE_URL }}'" >> .env
          echo "NEXT_PUBLIC_API_URL='${{ vars.BASE_URL }}'" >> .env
          echo "NEXT_PUBLIC_AZURE_CLIENT_ID='${{ vars.AZURE_CLIENT_ID }}'" >> .env
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID='${{ vars.GOOGLE_CLIENT_ID }}'" >> .env
          echo "NEXT_PUBLIC_ZOHO_CLIENT_ID='${{ vars.ZOHO_CLIENT_ID }}'" >> .env
          echo "NEXT_PUBLIC_HUBSPOT_CLIENT_ID='${{ vars.HUBSPOT_CLIENT_ID }}'" >> .env
          echo "NEXT_PUBLIC_GA_MEASUREMENT_ID='${{ vars.GA_MEASUREMENT_ID }}'" >> .env
      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy App to S3
        run: aws s3 sync ${{ vars.BUILD_PATH || 'out' }} ${{ vars.S3_BUCKET_PATH }} --delete

      - name: Invalidate CloudFront Caches
        if: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID != '' }}
        run: |
          for dist_id in $(echo "${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}" | tr ',' ' '); do
            echo "Starting invalidation for CloudFront distribution: $dist_id"
            aws cloudfront create-invalidation --distribution-id "$dist_id" --paths "/*" &
          done
          wait
